### PR TITLE
Add JuliaFormatter

### PR DESCRIPTION
**Pull request by odow**
Avoid the need for PRs like #110 or review comments like https://github.com/jump-dev/Dualization.jl/pull/111#discussion_r647081793.

### CODE REVIEW

**Review by guilhermebodin — APPROVED** [review]

**Comment by odow** [comment]
It's going to cause havoc with the two open PRs, but I suggest you either merge this once CI finishes, and then rebase the existing PRs on top, or merge the existing PRs without worrying about formatting and then rebase this.

**Comment by odow** [comment]
I'll rebase the PRs since I did this.

**Comment by guilhermebodin** [comment]
Thanks a lot @odow

**Comment by blegat** [comment]
I rebased https://github.com/jump-dev/Dualization.jl/pull/112

**Pull request merged**
