### PR TITLE
Don't create dual variables of constrained variables

### PR DESCRIPTION
**Pull request by blegat**
The tests and MOI wrapper still need to be updated.

Closes https://github.com/jump-dev/Dualization.jl/issues/27

### CODE REVIEW

**Comment by guilhermebodin** [comment]
@blegat I fixed the tests for many problems, but now it its breaking when dualization consider some variables as parameters.

**Comment by blegat** [comment]
> I fixed the tests for many problems, but now it its breaking when dualization consider some variables as parameters.

Thanks!
The test that was failing on CI was soc2 which was due to https://github.com/jump-dev/Dualization.jl/issues/108. Can you keep updating other tests so that the remaining ones are the parametrized tests ?

**Comment by guilhermebodin** [comment]
@blegat I fixed the missing tests.

**Comment by guilhermebodin** [comment]
But MOI.Wrapper is broken and CSDP tests were commented.

**Review by guilhermebodin — APPROVED** [review]

**Pull request merged**
